### sklearn.preprocessing.LabelEncoder

* _class_ sklearn.preprocessing.LabelEncoder[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/preprocessing/_label.py#L35)[](https://scikit-learn.org/1.1/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder "Permalink to this definition")


                                                       

In [12]:
from sklearn.preprocessing import LabelEncoder

items = ["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(f"인코딩 변환값 : {labels}, 인코딩 클래스 : {encoder.classes_} , 디코딩 원본 값 : {encoder.inverse_transform([4,5,2])}")


인코딩 변환값 : [0 1 4 5 3 3 2 2], 인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터'] , 디코딩 원본 값 : ['전자렌지' '컴퓨터' '믹서']


### sklearn.preprocessing.OneHotEncoder

* _class_ sklearn.preprocessing.OneHotEncoder(_*_, _categories='auto'_, _drop=None_, _sparse=True_, _dtype=<class  'numpy.float64'>_, _handle_unknown='error'_, _min_frequency=None_, _max_categories=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/preprocessing/_encoders.py#L201)[¶](https://scikit-learn.org/1.1/modules/generated/sklearn.preprocessing.OneHotEncoder.html?highlight=one+hot#sklearn.preprocessing.OneHotEncoder "Permalink to this definition")

Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or strings, denoting the values taken on by categorical (discrete) features. The features are encoded using a one-hot (aka ‘one-of-K’ or ‘dummy’) encoding scheme. This creates a binary column for each category and returns a sparse matrix or dense array (depending on the  `sparse`  parameter)

By default, the encoder derives the categories based on the unique values in each feature. Alternatively, you can also specify the  `categories`  manually.

This encoding is needed for feeding categorical data to many scikit-learn estimators, notably linear models and SVMs with the standard kernels.

Note: a one-hot encoding of y labels should use a LabelBinarizer instead.

Read more in the  [User Guide](https://scikit-learn.org/1.1/modules/preprocessing.html#preprocessing-categorical-features).


In [18]:
ohe.transform([["a"], ["b"]])

array([[0., 0., 1.],
       [1., 0., 0.]])

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

items = np.array(["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]).reshape(-1,1)


labels = encoder.transform(items)
oh_en = OneHotEncoder(sparse=False)
result= oh_en.fit_transform(items)
result

C:\Users\juno\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\juno\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [40]:
import pandas as pd 
pd.DataFrame(result, columns=["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "믹서"])

TV  냉장고  전자렌지  컴퓨터  선풍기   믹서
0  1.0  0.0   0.0  0.0  0.0  0.0
1  0.0  1.0   0.0  0.0  0.0  0.0
2  0.0  0.0   0.0  0.0  1.0  0.0
3  0.0  0.0   0.0  0.0  0.0  1.0
4  0.0  0.0   0.0  1.0  0.0  0.0
5  0.0  0.0   0.0  1.0  0.0  0.0
6  0.0  0.0   1.0  0.0  0.0  0.0
7  0.0  0.0   1.0  0.0  0.0  0.0

In [41]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

items = (["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"])

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print("원핫 인코딩 데이터", oh_labels.toarray(), "원핫 인코딩 데이터 차원", oh_labels.shape)

원핫 인코딩 데이터 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]] 원항 인코딩 데이터 차원 (8, 6)
